//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoAmlMiddleWare.Models
{

	public  class Country
    {
       public string lk_code { get; set; }
        public string lk_name { get; set; }
        public string lk_language { get; set; }
        public string lk_active { get; set; }
        public string lk_sys { get; set; }
        public string web_refresh { get; set; }
    
        
    }
}
